// The agent loop.
//
// Talks to whichever provider Settings currently points at (Ollama or
// OpenAI) through the OpenAI chat-completions API — Ollama via its
// OpenAI-compatible endpoint (/v1) rather than the native /api/chat. The
// compat layer gives real tool_call ids, so parallel tool calls pair up
// unambiguously, and it accepts image content blocks inside tool-result
// messages — which the vision escalation in tools.ts depends on.

import OpenAI from "openai";
import { emit } from "./bridge.js";
import {
  TOOL_DEFS,
  TOOL_BY_NAME,
  type ToolCtx,
  type ToolResult,
  type ContentPart,
} from "./tools.js";
import { getConfig, type LLMConfig } from "./config.js";
import {
  blank,
  listSessions,
  loadCurrent,
  loadSession,
  save,
  storageDir,
  type ApprovalMode,
  type Session,
  type SessionSummary,
} from "./session.js";

const MAX_STEPS = 60;

// Ollama ignores unknown top-level fields, so num_ctx rides along in the
// request body the same way the native API takes it under `options`.
type OllamaExtras = { options: { num_ctx: number } };

/** Cheap, never throws — just labels which model a chat was/is using. */
function activeLabel(cfg: LLMConfig): string {
  return cfg.provider === "openai"
    ? `openai:${cfg.openai.model}`
    : `ollama:${cfg.ollama.model}`;
}

/** Provider + model + a ready OpenAI-compatible client, resolved from the current settings. */
function resolveActive(cfg: LLMConfig) {
  if (cfg.provider === "openai") {
    if (!cfg.openai.apiKey) {
      throw new Error(
        "No OpenAI API key set. Add one in Settings, or switch the provider back to Ollama.",
      );
    }
    return {
      label: `openai:${cfg.openai.model}`,
      model: cfg.openai.model,
      client: new OpenAI({ apiKey: cfg.openai.apiKey }),
      extra: {} as Record<string, never>,
    };
  }
  return {
    label: `ollama:${cfg.ollama.model}`,
    model: cfg.ollama.model,
    client: new OpenAI({
      baseURL: `${cfg.ollama.host.replace(/\/$/, "")}/v1`,
      // Ollama does not check this, but the SDK refuses to construct without it.
      apiKey: process.env.OLLAMA_API_KEY ?? "ollama",
    }),
    extra: { options: { num_ctx: cfg.ollama.numCtx } } as OllamaExtras,
  };
}

// The chat is sticky, so it grows without bound unless something caps it.
// Roughly 4 chars per token, and leave room for the reply and the tools.
function historyBudgetChars(cfg: LLMConfig): number {
  if (process.env.HISTORY_BUDGET_CHARS)
    return Number(process.env.HISTORY_BUDGET_CHARS);
  if (cfg.provider === "ollama") return Math.floor(cfg.ollama.numCtx * 4 * 0.6);
  // OpenAI's hosted context windows are generous and not user-configured here.
  return 400_000;
}

// How many recent tool-result messages keep their full payload. Older ones get
// their images and long snapshot text stripped — see pruneHistory.
const KEEP_FULL = 3;
const STALE_TEXT_CAP = 600;

// Frozen prefix: this string must not vary between requests, or Ollama's
// prefix KV cache misses on every turn. Nothing dynamic goes in here.
const SYSTEM = `You control a real Chrome browser on the user's behalf, in their own profile with their existing logins.

<perception>
You see pages through \`snapshot\`, which returns the accessibility tree as lines like:
  [e12] textbox "Search" value=""
  [e28] button "Sign in"
The [eN] tokens are refs. Pass them to interaction tools. Refs are regenerated by every snapshot — a ref from an older snapshot may point somewhere else or nowhere.

When a page is icon-only or canvas-based, a badged screenshot is attached to the snapshot automatically. Red badge N means ref "eN".
</perception>

<workflow>
1. snapshot to see the current state
2. act using refs from that snapshot
3. snapshot again to confirm the result before deciding the next action
Do not chain several blind actions between snapshots — pages change underneath you.
</workflow>

<rules>
- Never guess a ref. On a stale-ref error, take a fresh snapshot and retry.
- Some buttons ("Apply now", "Continue", external links) open a new tab. When that happens you are switched to the new tab automatically and the tool result says so. Treat that as proof the action worked: never click it again, and snapshot before doing anything else because your old refs belong to the old tab.
- Close tabs you opened with close_tab once you are finished with them, and keep open the ones you will return to. When a task ends, tabs you opened are closed for you except the one you finish on — so if you will need a page again later, remember its URL.
- Prefer snapshot over screenshot; screenshots are expensive and less precise.
- Use read_page for reading and summarizing content, snapshot for finding controls.
- Fill form fields with paste, not type. Switch to type for search boxes that suggest as you type, one-box-per-character codes, and masked inputs like phone numbers or dates — and for any field paste reports it did not accept.
- If content you need is not in the snapshot, scroll and snapshot again.
- After clicking something that loads data without navigating, call wait_for_idle before the next snapshot.
- Set destructive=true on any click that purchases, sends, posts, deletes, or confirms something hard to undo. The user is asked to approve those.
- If the user declines an action, do not retry it. Explain the situation and stop.
- Never enter credentials, payment details, or other secrets. If a task requires signing in, stop and tell the user to sign in themselves, then continue.
- Older screenshots and page snapshots in this conversation are replaced with placeholders to save context. If you need to see the page again, take a fresh snapshot.
</rules>

<reporting>
When the task is done, state what you did and what you found. If you could not
complete it, say exactly where you stopped and why — do not claim success you
did not verify on screen.
</reporting>

<memory>
remember and search_memory persist facts about the user across chats, filed by topic (e.g. "user/career", "user/preferences").
- Call search_memory before a task that could reuse something you already know: filling a form, personalizing a choice, resuming a recurring job.
- Call remember when you learn something durable worth not re-learning next time — not one-off task details for this chat, and never passwords or other secrets.
- Reuse an existing topic when a fact fits one; only invent a new topic path when nothing existing does.
</memory>`;

// Injected once per resumed chat, right before the first new task. Filtered
// back out of replay() — it is a note to the model, not part of the chat.
const RESUME_NOTICE =
  "[Session resumed. The browser may have moved on since the messages " +
  "above: refs and screenshots from earlier turns are stale. Take a " +
  "fresh snapshot before acting on anything you saw before this line.]";

export type RunResult = {
  text: string;
  steps: number;
  usage: { input: number; output: number; cached: number };
  model: string;
};

type Msg = OpenAI.Chat.Completions.ChatCompletionMessageParam;

// Some OpenAI models (e.g. gpt-6-astra) reject reasoning_effort together with
// function tools on /v1/chat/completions ("use /v1/responses or set
// reasoning_effort to 'none'"). We stay on chat/completions and always send
// tools, so for those models reasoning_effort has to stay "none" for the rest
// of the process. Learned on first failure per model, not hardcoded, since
// most models (and Ollama) are fine with "high".
const noReasoningEffort = new Set<string>();

async function createCompletion(
  active: ReturnType<typeof resolveActive>,
  messages: Msg[],
  signal: AbortSignal,
) {
  const body = {
    model: active.model,
    max_completion_tokens: 16000,
    tools: TOOL_DEFS,
    reasoning_effort: noReasoningEffort.has(active.model) ? "none" : "high",
    messages,
    ...active.extra,
  } as OpenAI.Chat.Completions.ChatCompletionCreateParamsNonStreaming &
    OllamaExtras;

  try {
    return await active.client.chat.completions.create(body, { signal });
  } catch (err) {
    if (
      !noReasoningEffort.has(active.model) &&
      err instanceof OpenAI.APIError &&
      err.status === 400 &&
      /reasoning_effort/i.test(err.message)
    ) {
      noReasoningEffort.add(active.model);
      return active.client.chat.completions.create(
        { ...body, reasoning_effort: "none" },
        { signal },
      );
    }
    throw err;
  }
}

// Stand-in for Anthropic's clear_tool_uses_20250919, which the compat endpoint
// has no equivalent for. Without it, every superseded snapshot and screenshot
// is resent on every turn — dead page state that also tempts the model into
// reusing refs that no longer exist. Rewrites in place on a copy; the
// tool_call_id pairing is preserved, because dropping a tool message outright
// would make the request invalid.
function pruneHistory(messages: Msg[]): Msg[] {
  const toolIdx = messages.reduce<number[]>(
    (acc, m, i) => (m.role === "tool" ? (acc.push(i), acc) : acc),
    [],
  );
  const stale = new Set(
    toolIdx.slice(0, Math.max(0, toolIdx.length - KEEP_FULL)),
  );
  if (stale.size === 0) return messages;

  return messages.map((m, i) => {
    if (!stale.has(i) || m.role !== "tool") return m;
    const content = m.content;
    if (typeof content === "string") {
      return content.length > STALE_TEXT_CAP
        ? {
            ...m,
            content: `${content.slice(0, STALE_TEXT_CAP)}\n… (superseded, re-snapshot to see current state)`,
          }
        : m;
    }
    // OpenAI's types declare tool-result content as text-only; we actually
    // send images through it, so widen to what is really there.
    let hadImage = false;
    const parts = (content as unknown as ContentPart[]).flatMap<ContentPart>(
      (p) => {
        if (p.type === "image_url") {
          hadImage = true;
          return [];
        }
        if (p.type === "text" && p.text.length > STALE_TEXT_CAP) {
          return [
            {
              ...p,
              text: `${p.text.slice(0, STALE_TEXT_CAP)}\n… (superseded)`,
            },
          ];
        }
        return [p];
      },
    );
    if (hadImage) {
      parts.push({
        type: "text",
        text: "(screenshot cleared from context — take a fresh one if needed)",
      });
    }
    return { ...m, content: parts as unknown as typeof content };
  });
}

/**
 * Drop whole turns off the front until the transcript fits the budget.
 *
 * The cut has to land on a user message. Every other boundary risks splitting
 * an assistant message from the tool results its tool_calls demand, which the
 * API rejects — and tool results are role "tool" here, so a "user" message is
 * always the start of a turn.
 */
function trimTurns(history: Msg[], budget: number): Msg[] {
  const starts = history.reduce<number[]>(
    (acc, m, i) => (m.role === "user" ? (acc.push(i), acc) : acc),
    [],
  );
  let out = history;
  // Never drop the turn in progress, however big it got.
  for (let cut = 1; cut < starts.length; cut++) {
    if (JSON.stringify(out).length <= budget) break;
    out = history.slice(starts[cut]);
  }
  return out;
}

/**
 * One Agent per chat, for the chat's whole lifetime — there is no more
 * process-wide "current" agent. index.ts keeps a registry keyed by chat id
 * and looks one of these up (or creates it) whenever a chat needs one.
 */
export class Agent {
  private abort: AbortController | null = null;
  private session: Session;
  // Earlier turns describe pages that have since moved on; the model gets
  // told once, on the first task after a chat is loaded from disk.
  private resumeNoticePending: boolean;

  private constructor(session: Session) {
    this.session = session;
    this.resumeNoticePending = session.messages.length > 0;
  }

  /** A brand-new, empty chat — never resumes anything. */
  static blank(): Agent {
    return new Agent(blank(activeLabel(getConfig())));
  }

  /** The last-viewed chat (current.json), or a blank one if there is none yet. */
  static async resumeLast(): Promise<Agent> {
    return new Agent(await loadCurrent(activeLabel(getConfig())));
  }

  /** A specific past chat by id. Falls back to a blank chat under that same id if it is somehow gone. */
  static async forChat(id: string): Promise<Agent> {
    const label = activeLabel(getConfig());
    try {
      return new Agent(await loadSession(id, label));
    } catch {
      return new Agent({ ...blank(label), id });
    }
  }

  info() {
    return {
      id: this.session.id,
      turns: this.session.tasks.length,
      messages: this.session.messages.length,
      approvalMode: this.session.settings.approvalMode,
      dir: storageDir,
    };
  }

  setApprovalMode(mode: ApprovalMode): Promise<void> {
    this.session.settings.approvalMode = mode;
    return this.persist();
  }

  cancel() {
    this.abort?.abort();
  }

  /**
   * A simplified transcript of the active chat for the popup to render: what
   * was asked and the final answer to each turn. The step-by-step tool
   * actions in between are live-only (see bridge.ts emit()) and were never
   * written to disk, so a reopened or switched-to chat cannot show them —
   * only the conversation itself.
   */
  replay(): { event: string; text: string }[] {
    const out: { event: string; text: string }[] = [];
    for (const m of this.session.messages) {
      if (m.role === "user" && typeof m.content === "string") {
        if (m.content === RESUME_NOTICE) continue;
        out.push({ event: "start", text: m.content });
      } else if (
        m.role === "assistant" &&
        typeof m.content === "string" &&
        m.content.trim()
      ) {
        out.push({ event: "say", text: m.content });
      }
    }
    return out;
  }

  async run(task: string): Promise<RunResult> {
    this.abort = new AbortController();

    // Resolved once per run: the model a task started with sees it through,
    // even if Settings is changed while it is still working.
    const active = resolveActive(getConfig());
    this.session.model = active.label;
    const budget = historyBudgetChars(getConfig());

    if (this.resumeNoticePending) {
      this.session.messages.push({ role: "user", content: RESUME_NOTICE });
      this.resumeNoticePending = false;
    }

    // A task is a turn, not a new conversation.
    this.session.messages.push({ role: "user", content: task });
    this.session.tasks.push(task);

    const usage = { input: 0, output: 0, cached: 0 };
    let steps = 0;
    let finalText = "";

    while (steps < MAX_STEPS) {
      if (this.abort.signal.aborted) {
        await this.persist();
        return {
          text: "Cancelled by user.",
          steps,
          usage,
          model: active.label,
        };
      }
      steps++;

      this.session.messages = trimTurns(
        pruneHistory(this.session.messages),
        budget,
      );
      // The system prompt is a frozen constant and is never stored, so it is
      // prepended per request rather than kept in the transcript.
      const messages: Msg[] = [
        { role: "system", content: SYSTEM },
        ...this.session.messages,
      ];

      const res = await createCompletion(active, messages, this.abort.signal);

      usage.input += res.usage?.prompt_tokens ?? 0;
      usage.output += res.usage?.completion_tokens ?? 0;
      usage.cached += res.usage?.prompt_tokens_details?.cached_tokens ?? 0;

      const choice = res.choices[0];
      if (!choice)
        throw new Error("Ollama returned no choices — is the model loaded?");
      const msg = choice.message;

      this.session.messages.push(msg);

      // Non-standard field: Ollama surfaces thinking-model output here rather
      // than in content. Shown to the user, never fed back to the model.
      const reasoning = (msg as { reasoning?: string }).reasoning;
      if (reasoning?.trim()) emit("think", this.session.id, reasoning);

      if (msg.content?.trim()) {
        finalText = msg.content;
        emit("say", this.session.id, msg.content);
      }

      const calls = msg.tool_calls ?? [];
      if (calls.length === 0) {
        await this.persist();
        break;
      }

      for (const c of calls) {
        // The compat endpoint only emits function calls, but the union in the
        // SDK also covers custom tools.
        if (c.type !== "function") {
          this.session.messages.push({
            role: "tool",
            tool_call_id: c.id,
            content: `Unsupported tool call type "${c.type}".`,
          });
          continue;
        }
        const tool = TOOL_BY_NAME.get(c.function.name);
        if (!tool) {
          this.session.messages.push({
            role: "tool",
            tool_call_id: c.id,
            content: `No such tool "${c.function.name}".`,
          });
          continue;
        }
        try {
          // Local models emit malformed argument JSON often enough that this
          // has to be a normal tool error the model can read and retry, not a
          // crash of the run.
          let input: unknown;
          try {
            input = c.function.arguments
              ? JSON.parse(c.function.arguments)
              : {};
          } catch {
            throw new Error(
              `Arguments were not valid JSON: ${c.function.arguments}. Re-issue the call with valid JSON.`,
            );
          }
          const ctx: ToolCtx = {
            chatId: this.session.id,
            approvalMode: this.session.settings.approvalMode,
            signal: this.abort.signal,
          };
          const out: ToolResult = await tool.run(input, ctx);
          this.session.messages.push({
            role: "tool",
            tool_call_id: c.id,
            content: out as any,
          });
        } catch (err) {
          // Failures are values, not exceptions. A stale ref or a timeout is
          // recoverable and the model handles it well when it can see it.
          const text = String((err as Error)?.message ?? err);
          emit("tool-error", this.session.id, `${c.function.name}: ${text}`);
          this.session.messages.push({
            role: "tool",
            tool_call_id: c.id,
            content: `Error: ${text}`,
          });
        }
      }

      // Written every step, so an interrupted run still leaves a resumable
      // chat rather than losing the whole turn.
      await this.persist();
    }

    if (steps >= MAX_STEPS) {
      finalText ||= `Stopped after ${MAX_STEPS} steps without finishing.`;
    }
    await this.persist();
    return { text: finalText, steps, usage, model: active.label };
  }

  private async persist() {
    try {
      await save(this.session);
    } catch (err) {
      // A failed write must not take the run down with it.
      console.error(`[session] could not save transcript: ${String(err)}`);
    }
  }
}

export function formatUsage(r: Pick<RunResult, "usage" | "model">): string {
  return `in ${r.usage.input} (cached ${r.usage.cached}) · out ${r.usage.output} · ${r.model}`;
}

/** Every saved chat, newest first, flagged with which ones are running right now. */
export async function listChats(
  runningIds: Set<string>,
): Promise<(SessionSummary & { running: boolean })[]> {
  const chats = await listSessions();
  // A chat with nothing said in it yet is not worth its own history entry —
  // unless it is somehow already running (defensive; practically never true,
  // since a task pushes its own text into `tasks` before the run starts).
  return chats
    .filter((s) => s.taskCount > 0 || runningIds.has(s.id))
    .map((s) => ({ ...s, running: runningIds.has(s.id) }));
}

/** Human-readable label for whatever provider/model Settings currently point at. */
export function activeModelLabel(): string {
  return activeLabel(getConfig());
}
